#!/usr/bin/env sh


# import the colors
. "${HOME}/.cache/wal/colors.sh"

# bar
SPACEBAR_HEIGHT=$(spacebar -m config height)
ps cax | grep spacebar &> /dev/null
if [ $? -eq 0 ] ; then
    yabai -m config external_bar all:$SPACEBAR_HEIGHT:0
    yabai -m config top_padding 10
else 
    yabai -m config external_bar all:0:0
    yabai -m config top_padding 10
fi

# set border colors
yabai_color

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          autoraise
yabai -m config window_placement             second_child
yabai -m config window_topmost               on
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config window_shadow                off
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.9
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               cmd
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  10
yabai -m config bottom_padding               10
yabai -m config left_padding                 10
yabai -m config right_padding                10
yabai -m config window_gap                   10

# borders
yabai -m config window_border                on
yabai -m config window_border_width          6
yabai -m config active_window_border_color   0xff"${color7//#}"
yabai -m config normal_window_border_color   0xff"${color8//#}"

# rules
yabai -m rule --add app="^System Preferences$" layer=above manage=off border=off
yabai -m rule --add app="^csgo_osx64$" border=off
yabai -m rule --add app="^qutebrowser$" manage=on

# signals
yabai -m signal --add event=window_destroyed action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"
yabai -m signal --add event=application_terminated action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"

# autoupdate
# YABAI_CERT=yabai-cert sh -c "$(curl -fsSL "https://git.io/update-yabai")" &
