#!/usr/bin/env sh

spacebar -m config text_font         "SF Pro Text:Bold:12.0"
spacebar -m config icon_font         "FontAwesome:Regular:12.0"
spacebar -m config background_color  0xff202020
spacebar -m config foreground_color  0xffa8a8a8
spacebar -m config space_icon_strip  I II III IV V VI VII VIII IX X
spacebar -m config power_icon_strip   
spacebar -m config space_icon        
spacebar -m config clock_icon        
