#!/usr/bin/env sh

# Import the colors
. "${HOME}/.cache/wal/colors.sh"

spacebar -m config text_font         "SF Pro Text:Bold:12.0"
spacebar -m config icon_font         "SF Mono Square:Regular:14.0"
spacebar -m config background_color  0xff"${color0//#}"
spacebar -m config foreground_color  0xff"${color7//#}"
spacebar -m config space_icon_strip  一 二 三 四 五 六 七 八 九 十
spacebar -m config power_icon_strip   
spacebar -m config space_icon        
spacebar -m config clock_icon        
