#!/usr/bin/env bash

finder() {
	osascript <<-EOD
		tell application "Finder"
			set myW to make new Finder window
			set target of myW to home
			activate
			set toolbar visible of every Finder window to 1
			tell column view options of every Finder window
				set shows icon to true
				set shows icon preview to true
				set shows preview column to true
				set discloses preview pane to true
			end tell
		end tell
	EOD
}

safari() {
	osascript <<-EOD
		tell application "Safari"
			make new document with properties {URL:"file:///Users/zzzeyez/scripts/pollen/index.html"}
			activate
		end tell
	EOD
}

iterm2() {
	i="$(ps cax | grep iTerm2)"
	if [[ ! "$i" ]] ; then
		open -a iTerm
	else
		osascript <<-EOD
			tell application "iTerm"
				activate
			end tell
			tell application "System Events" to tell process "iTerm"
				keystroke "n" using command down
			end tell
		EOD
	fi
}

# firefox() {
#         osascript <<-EOD
#                 tell application "Firefox"
#                         activate
#                 end tell
#                 tell application "System Events"
#                         keystroke "n" using command down
#                 end tell
#         EOD
# }

if [ $1 = "finder" ]; then
	finder
elif [ $1 = "safari" ]; then
	safari
elif [ $1 = "iterm2" ]; then
	iterm2
# elif [ $1 = "firefox" ]; then
#         firefox
fi
