#!/usr/bin/env bash


# current_padding = $(yabai -m config window_gap)
# declare -i current_padding

ps cax | grep spacebar > /dev/null
if [ $? -eq 0 ] ; then
	launchctl unload /usr/local/opt/spacebar/homebrew.mxcl.spacebar.plist
	yabai -m config external_bar all:0:0
	spacebar -m config height 0
	# yabai -m config top_padding $((current_padding * 2))
else
	launchctl load /usr/local/opt/spacebar/homebrew.mxcl.spacebar.plist
	yabai -m config external_bar all:25:0
	spacebar -m config height 25
	# yabai -m config top_padding $((current_padding * 2))
fi

# ps cax | grep bersicht > /dev/null
# if [ $? -eq 0 ]; then
# 	ubersicht_pid=$(ps cax | grep bersicht | awk '{print $1}')
# 	kill $ubersicht_pid &
# 	yabai -m config external_bar all:0:0
# 	spacebar -m config height 0
# else
# 	open /Applications/Übersicht.app
# 	yabai -m config external_bar all:28:0
# 	spacebar -m config height 25
# fi
