#!/usr/bin/env bash


is_floating="$(yabai -m query --windows --window | jq .floating)"
if [ $is_floating -eq 0 ] ; then
	west()  { yabai -m window --warp west ;}
	south() { yabai -m window --warp south ;}
	north() { yabai -m window --warp north ;}
	east()  { yabai -m window --warp east ;}
else
	west()  { yabai -m window --move rel:-20:0 ;}
	south() { yabai -m window --move rel:0:20 ;}
	north() { yabai -m window --move rel:0:-20 ;}
	east()  { yabai -m window --move rel:20:0 ;}
fi

case "$1" in
	west)  west ;;
	south) south ;;
	north) north ;; 
	east)  east ;;
esac
