#!/usr/bin/env bash


ps cax | grep spacebar > /dev/null
if [ $? -eq 0 ] ; then
	launchctl unload /usr/local/opt/spacebar/homebrew.mxcl.spacebar.plist
	yabai -m config external_bar all:0:0
	yabai -m config top_padding 10
else
	launchctl load /usr/local/opt/spacebar/homebrew.mxcl.spacebar.plist
	yabai -m config external_bar all:26:0
	yabai -m config top_padding 10
fi
