#!/usr/bin/env bash


scratchpad_id=$(yabai -m query --windows | jq '.[] | select(.title=="Scratchpad").id')

if [[ "$scratchpad_id" -lt 1 ]]; then
  yabai -m signal --add label=float_next_window_created event=window_created action='yabai -m signal --remove float_next_window_created; yabai -m signal --remove float_next_application_launched; yabai -m window $YABAI_WINDOW_ID --toggle float; yabai -m window --grid 4:4:1:1:2:2'
  yabai -m signal --add label=float_next_application_launched event=application_launched action='yabai -m signal --remove float_next_window_created; yabai -m signal --remove float_next_application_launched; yabai -m query --windows | jq -r ".[] | select(.pid == $YABAI_PROCESS_ID).id" | xargs -I{} yabai -m window {} --toggle float; yabai -m window --grid 4:4:1:1:2:2'
  /Applications/Alacritty.app/Contents/MacOS/alacritty --title Scratchpad
  # yabai -m window --focus "$scratchpad_id"
else
  is_minimized=$(yabai -m query --windows --window "$scratchpad_id" | jq '.minimized')
  current_space=$(yabai -m query --spaces --space | jq '.index')
  if [[ "$is_minimized" -eq 1 ]]; then
    yabai -m window "$scratchpad_id" --space "$current_space"
    yabai -m window --focus "$scratchpad_id"
    yabai -m window --grid 4:4:1:1:2:2
  else
    yabai -m window "$scratchpad_id" --minimize
    yabai -m window --focus mouse
  fi
fi
