#!/usr/bin/env bash


is_floating="$(yabai -m query --windows --window | jq .floating)"
if [ $is_floating -eq 0 ] ; then
    if [ "$1" == "west" ] ; then
	yabai -m window west --resize right:-20:0 2> /dev/null || yabai -m window --resize right:-20:0
    elif [ "$1" == "south" ] ; then
	yabai -m window north --resize bottom:0:20 2> /dev/null || yabai -m window --resize bottom:0:20
    elif [ "$1" == "north" ] ; then
	yabai -m window south --resize top:0:-20 2> /dev/null || yabai -m window --resize top:0:-20
    elif [ "$1" == "east" ] ; then
	yabai -m window east --resize left:20:0 2> /dev/null || yabai -m window --resize left:20:0
    fi
else
    if [ "$1" == "west" ] ; then
	yabai -m window --resize right:-20:0
    elif [ "$1" == "south" ] ; then
	yabai -m window --resize bottom:0:20
    elif [ "$1" == "north" ] ; then
	yabai -m window --resize bottom:0:-20
    elif [ "$1" == "east" ] ; then
	yabai -m window --resize right:20:0
    fi
fi
